export default {
  CONFIG: {
    // Credentials: 'config_credentials',
  },
  GENERAL: {},
  USER: {
    LOGIN: 'USER_LOGIN',
    LOGOUT: 'USER_LOGOUT',
    SIGNUP: 'USER_SIGNUP',
    REGISTER: 'USER_REGISTER',
    REFRESH: 'REFRESH_TOKEN',
    REFRESH_START: 'REFRESH_TOKEN_START',
    REFRESH_STOP: 'REFRESH_TOKEN_STOP',
    EDIT: 'EDIT_USER',
    DETAILS: 'USER_DETAILS',
    SURFER_DETAILS: 'SURFER_DETAILS',
    USERS_LIST_DETAILS: 'USERS_LIST_DETAILS',
    AVATAR: 'UPLOAD_AVATAR',
    GET_MESSAGES: 'GET_MESSAGES',
    SEND_MESSAGE: 'SEND_MESSAGE',
    FOLLOW: 'USER_FOLLOW',
    IMAGE_UPLOAD: 'IMAGE_UPLOAD',
    FORGOT: 'USER_FORGOT',
    RESET:'USER_RESET',
    MSG_UPDATE:'USER_MSG_UPDATE'
  },
  TRIP: {
    CREATE: 'TRIP_CREATE',
    FETCH: 'TRIP_FETCH',
    FETCH_ALL: 'TRIP_FETCH_ALL',
    FETCH_OWN: 'TRIP_FETCH_OWN',
    FETCH_USER: 'TRIP_FETCH_USER',
    DELETE: 'TRIP_DELETE',
    SET_CURRENT: 'SET_CURRENT',
    JOIN: 'TRIP_JOIN',
    LEAVE: 'TRIP_LEAVE',
    FILTER: 'TRIP_FILTER',
    FILTER_QUERY: 'TRIP_FILTER_QUERY',
    ATTENDEE_DETAIL: 'ATTENDEE_DETAIL',
    SEARCH_PARAM: 'SEARCH_PARAM'
  }
}
