export default {
  DASHBOARD: 'dashboard',
  SEARCH: 'search',
  SURFTRIPS: 'surftrips',
  PROFILE: 'profile',
  LOGIN: 'login',
  ONBOARD: 'signup',
  TERMS: 'terms',
  PRIVACY: 'policies',
  TRIP: 'trip',
  CREATE: 'create-trip',
  MAIL: 'inbox',
  EDIT_TRIP: 'edit_trip',
  EDIT_PROFILE: 'edit_profile',
  USER: 'user',
  USERS: 'users',
  AUTH: 'auth',
  FORGOT: 'forgot',
  MESSAGE: 'message',
  RESET_PASSWORD: 'reset_password'
}
